model: "weights/depth_anything_v2_vits_dynamic.onnx"
eval:
  test_dir: "data/nyu2_test"
  input_res: full # change to `reduced` to infer 224x224 images during eval
  input_height: 480
  input_width: 640
  min_depth: 1e-3
  max_depth: 1
  batch_size: 1 # The 'dynamic' model supports batched inputs, but metrics don't (for now)
